[package]
name = "seda-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
jsonrpsee = { workspace = true }
parking_lot = { workspace = true }
reqwest = { workspace = true }
seda-chain-adapters = { workspace = true }
seda-runtime-adapters = { workspace = true }
seda-config = { workspace = true }
seda-runtime = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
