[package]
name = "seda-node"
version = "0.1.0"
edition = "2021"
<<<<<<< HEAD
build = "build.rs"
=======

[features]
default = []
near = ["seda-config/near"]
>>>>>>> 0d4f84b (refactor: runtime works with cfg)

[dependencies]
actix = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
jsonrpsee = { workspace = true }
jsonrpsee-ws-server = { workspace = true }
parking_lot = { workspace = true }
reqwest = { workspace = true }
seda-chain-adapters = { workspace = true }
seda-config = { workspace = true }
seda-p2p-adapters = { workspace = true }
seda-runtime = { workspace = true }
seda-runtime-adapters = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
