[package]
name = "seda-node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = { version = "0.13.0" }
tokio = { version = "1.21.2", features = ["full"] }
jsonrpsee-ws-server = "0.15.1"
serde_json = "1.0.87"
jsonrpsee-core = "0.15.1"
seda-adapters = {path = "../adapters"}