[package]
name = "seda-token"
version = "1.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
schemars = { workspace = true }
near-sdk = { workspace = true, features = ["legacy", "unit-testing"] }
near-contract-standards = { workspace = true }
