[package]
name = "seda-runtime"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.58"
error-stack = "0.2.3"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
thiserror = "1.0.37"
toml = { version = "0.5.9", default-features = false }
wasmer = "2.3.0"
wasmer-wasi = "2.3.0"
serde_json = "1.0"
mockall = "0.11.3"
seda-runtime-macros = { path = "../macros" }
seda-runtime-sdk = { path = "../sdk" }
reqwest = "0.11.12"
parking_lot = "0.12"
tokio = { version = "1.21.2", features = [
	"rt",
	"macros",
	"sync",
	"rt-multi-thread",
] }


rusqlite = "0.28.0"