[package]
name = "seda-runtime-sdk"
version = "0.1.0"
edition = "2021"

[features]
default = []
wasm = []

[dependencies]
clap = { workspace = true, features = ["derive", "std"] }
serde = { workspace = true }
serde_json = { workspace = true }
